#!/bin/bash
set -xe

# Drush executable.
[[ $DRUSH && ${DRUSH-x} ]] || DRUSH=drush

# Build base.
[[ $BUILD_ROOT && ${BUILD_ROOT-x} ]] || BUILD_ROOT="."

# Move to the top directory.
ROOT=$(git rev-parse --show-toplevel)
cd $ROOT

# Chores.
(
  for DIR in $BUILD_ROOT/www-build sites-backup idea/1 idea/modules/contrib idea/themes/contrib idea/libraries; do
    rm -Rf $DIR
  done
)

# Remove downloadable components
(
  rm -rf idea/modules/contrib
  rm -rf idea/modules/themes
  rm -rf www
)

# Build the profile itself.
(
  cd idea
  $DRUSH make --no-core --contrib-destination drupal-org.make .
  cd ..
)

# Build core and move the profile in place.
(
  # Build core.
  $DRUSH make idea/build-openideal.make $BUILD_ROOT/www-build

  # Check if sites/default exists, which means it is an existing installation.
  if [ -d $BUILD_ROOT/www/sites/default ]; then
    cp -rp $BUILD_ROOT/www/sites/default sites-backup
  fi

  # Restore the sites directory.
  if [ -d sites-backup ]; then
    rm -Rf $BUILD_ROOT/www-build/sites/default
    mv sites-backup/ $BUILD_ROOT/www-build/sites/default
  fi

  # Move the profile in place.
  rm -rf $BUILD_ROOT/www-build/profiles/idea
  ln -s ../../idea $BUILD_ROOT/www-build/profiles/idea

  # Fix permisions before deleting.
  chmod -R +w $BUILD_ROOT/www/sites/* || true
  rm -Rf $BUILD_ROOT/www || true

  # Restore updated site.
  mv $BUILD_ROOT/www-build $BUILD_ROOT/www
)
